// tag::metadata[]
:lang: en
include::../locale/attributes.adoc[]

// MANDATORY. Title of the document. In web format, It appears as a heading of
// level 1. In PDF format, it appears in a title page.
:_title:

// OPTIONAL. If not blank, it must begin with ": " (colon followed by a blank
// space). In web format, it appears as part of the same heading of level 1 than
// the title. In PDF format, it appears in the title page, just below the title.
:_subtitle:

// It's usually not necessary to change this field.
:doctitle: {_title}{_subtitle}

// MANDATORY. Numeric revision in X.Y.Z format, where X, Y and Z are numbers,
// and Z is optional.
:revnumber:

// OPTIONAL. Publication date of the revision. When the default value
// ("{docdate}") is used, the current date in format YYYY-MM-DD is automatically
// inserted in this field every time the formatted document (web or PDF) is
// generated. It's also possible to manually write here a fixed date.
:revdate: {docdate}

// OPTIONAL. See this field description in section "Authorship criteria ..."
// below.
:_editors:

// MANDATORY. See this field description in section "Authorship criteria ..."
// below.
:authors:

// OPTIONAL. See this field description in section "Authorship criteria ..."
// below.
:_contributors:

// OPTIONAL. See this field description in section "Authorship criteria ..."
// below.
:_proofreaders:

// OPTIONAL. See this field description in section "Authorship criteria ..."
// below.
:_participants:

// MANDATORY. Summary of the contents of the document. This would correspond to
// the "abstract" in an academic publication.
:_summary:

// MANDATORY. Comma-separated list of terms to help classifying and searching
// the document. In web format, this terms are integrated as SEO enabling
// metadata. In PDF format, they are shown near the other metadata.
:keywords:

// MANDATORY. Document's history.
:_dochistory:

// MANDATORY. When the document is not in its 1.0 release, yet, we can write "WE
// URGE YOU NOT TO CITE THIS YET UNTIL REVISION 1.0" Variables like {_title},
// {authors}, {doctitle} or {revnumber} can be used here.
:_citation:

// end::metadata[]

// tag::metadata-table[]

== Metadata

[cols="20,80"]
|===
| Title                                 | {_title}
| Version                               | {revnumber}
| Date                                  | {revdate}
| Editors                               | {_editors}
| Authors                               | {authors}
| Contributors                          | {_contributors}
| Proofreaders                          | {_proofreaders}
| Participants                          | {_participants}
| Summary                               | {_summary}
| Keywords                              | {keywords}
| Document history                      | {_dochistory}
| How to cite                           | {_citation}
| Copyleft
a| Barcelona City Council and the authors of the text, under a Creative Commons Attribution-ShareAlike 4.0 International (CC-BY-SA-4.0) licence and the GNU Free Documentation licence (GFDL-1.3-or-later).

[discrete]
===== Creative Commons Attribution-ShareAlike 4.0 International (CC-BY-SA-4.0)

You are free to copy and redistribute the material in any medium or format, remix, transform and build upon material, for any purpose, even commercially. The licensor may not revoke these freedoms as long as you comply with the licence's terms. Under the following conditions: a) Attribution: you must provide an appropriate acknowledgement of the authorship, provide a link to the licence and state whether any changes have been made. You may do that in any reasonable way, but not in a way that would suggest you have the licensor's support or receive it for the use you are making; b) ShareAlike: where you remix change or create from the material, you will have to disseminate your contributions under the same licence as the original. There are no additional restrictions, you may not apply legal terms or technological measures that legally restrict others from doing anything the licence permits. You can find full licences on the following links: https://creativecommons.org/licenses/by-sa/4.0/deed.

[discrete]
===== GNU Free Documentation Licence (GFDL-1.3-or-later)

You are permitted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation Licence, version 1.3 or any other version subsequently published by the Free Software Foundation; without Invariant Sections or Front-Cover Texts, or Back-Cover Texts either. You can find a copy of the licence on http://www.gnu.org/copyleft/fdl.html.
|===

// end::metadata-table[]

// tag::contributing[]

== Authorship criteria and how to contribute to this document

This document is open to participation. You may contribute to this document in several different ways. Except for the editing function, all other forms of participation and authorship levels and criteria are stated below:

Editors :: Responsible for monitoring a text and its versions, corrections and structure etc., and may or may not be one of the authors. In essence, an editor is someone who coordinates collaboration on the text. One of the editor's responsibilities is to request and read revisions.

Authors :: Strictly speaking, authors are those who have drafted the text. The order of the authors listed reflects their contribution, with the first mentioned being the one who has written the most. Authors must have read and revised their text in its final or previous versions, although they do not have to agree with its final form, a task that falls to the editor.

Contributors :: Two groups of contributors are considered here. On the one hand, the document's academic revisers (where they have made a considerable contribution) and, on the other, external collaborators whose contributions have been valuable and integrated in parts of the text included in the document. It is up to the editor and other authors to decide who is a contributor or an author, although the former is in any case meant to contribute less than the latter. As a general rule, a person who has written under 10% of the text ought to be considered a contributor rather than an author. By the same token, being a contributor means having written at least two or three paragraphs.

Participants :: This is someone who has not contributed any specific text to the document but who has made valuable contributions such as observations about the document or provided valuable criteria, references or elements of discussion.

Proofreaders :: Their work includes carefully reading an entire text, correcting errors and suggesting improvements. Such work is generally commissioned (requested from a person regarded as competent in the field), although it is possible for someone to contribute by proofreading a text that has not been explicitly requested. In such cases, the depth and quality of the proofreading process may qualify a person to be considered as a proofreader.footnote:[This division and specification of authorship levels has been copied directly from the criteria established under http://floksociety.org/[the FLOK Society - Buen conocer] (see http://book.floksociety.org/ec/[Barandiaran et al. 2015], pp. 38-39).]

// end::contributing[]
