// tag::metadata[]
:lang: ca
include::../locale/attributes.adoc[]

// MANDATORY. Title of the document. In web format, It appears as a heading of
// level 1. In PDF format, it appears in a title page.
:_title:

// OPTIONAL. If not blank, it must begin with ": " (colon followed by a blank
// space). In web format, it appears as part of the same heading of level 1 than
// the title. In PDF format, it appears in the title page, just below the title.
:_subtitle:

// It's usually not necessary to change this field.
:doctitle: {_title}{_subtitle}

// MANDATORY. Numeric revision in X.Y.Z format, where X, Y and Z are numbers,
// and Z is optional.
:revnumber:

// OPTIONAL. Publication date of the revision. When the default value
// ("{docdate}") is used, the current date in format YYYY-MM-DD is automatically
// inserted in this field every time the formatted document (web or PDF) is
// generated. It's also possible to manually write here a fixed date.
:revdate: {docdate}

// OPTIONAL. See this field description in section "Authorship criteria ..."
// below.
:_editors:

// MANDATORY. See this field description in section "Authorship criteria ..."
// below.
:authors:

// OPTIONAL. See this field description in section "Authorship criteria ..."
// below.
:_contributors:

// OPTIONAL. See this field description in section "Authorship criteria ..."
// below.
:_proofreaders:

// OPTIONAL. See this field description in section "Authorship criteria ..."
// below.
:_participants:

// MANDATORY. Summary of the contents of the document. This would correspond to
// the "abstract" in an academic publication.
:_summary:

// MANDATORY. Comma-separated list of terms to help classifying and searching
// the document. In web format, this terms are integrated as SEO enabling
// metadata. In PDF format, they are shown near the other metadata.
:keywords:

// MANDATORY. Document's history.
:_dochistory:

// MANDATORY. When the document is not in its 1.0 release, yet, we can write "WE
// URGE YOU NOT TO CITE THIS YET UNTIL REVISION 1.0" Variables like {_title},
// {authors}, {doctitle} or {revnumber} can be used here.
:_citation:

// end::metadata[]

// tag::metadata-table[]

== Metadades

[cols="20,80"]
|===
| Títol                                 | {_title}
| Versió                                | {revnumber}
| Data                                  | {revdate}
| Edició                                | {_editors}
| Autoria                               | {authors}
| Contribució                           | {_contributors}
| Revisió                               | {_proofreaders}
| Participació                          | {_participants}
| Resum                                 | {_summary}
| Paraules clau                         | {keywords}
| Història del document                 | {_dochistory}
| Com es cita                           | {_citation}
| Copyleft
a| Ajuntament de Barcelona i persones autores del text, sota les llicències Creative Commons Reconeixement-CompartirIgual Internacional 4.0 (CC-BY-SA-4.0) i Llicència de documentació lliure de GNU (GFDL-1.3-or-later).

[discrete]
===== Creative Commons Reconeixement-CompartirIgual 4.0 Internacional (CC-BY-SA-4.0)

Sou lliures de copiar i redistribuir el material en qualsevol mitjà o format, remesclar, transformar i crear a partir del material, per a qualsevol finalitat, fins i tot comercial. El llicenciador no pot revocar aquestes llibertats mentre compliu amb els termes de la llicència. Sota les condicions següents: a) Reconeixement: heu de reconèixer adequadament l'autoria, proporcionar un enllaç a la llicència i indicar si s'hi han fet canvis. Podeu fer-ho de qualsevol manera raonable, però no d'una manera que suggereixi que teniu el suport del llicenciador o el rebeu per l'ús que en feu; b) Compartir igual: si remescleu, transformeu o creeu a partir del material, haureu de difondre les vostres contribucions sota la mateixa llicència que l'original. No hi ha restriccions addicionals, no podeu aplicar termes legals o mesures tecnològiques que legalment restringeixin fer allò que la llicència permet. Podeu trobar les llicències completes en els enllaços següents: https://creativecommons.org/licenses/by-sa/4.0/deed.ca.

[discrete]
===== Llicència de documentació lliure de GNU (GFDL-1.3-or-later)

Es concedeix permís per copiar, distribuir o modificar aquest document sota els termes de la llicència de documentació lliure GNU, versió 1.3 o qualsevol altra versió posterior publicada per la Free Software Foundation; sense seccions invariants ni textos de coberta davantera, tampoc textos de contraportada. Una còpia de la llicència es pot trobar a http://www.gnu.org/copyleft/fdl.html.
|===

// end::metadata-table[]

// tag::contributing[]

== Criteris d'autoria i com participar en aquest document

Aquest document està obert a la participació. Podeu contribuir-hi de diverses maneres. Excepte la funció d'edició, la resta de les formes de participació i els nivells i criteris d'autoria s'especifiquen a continuació:

Editor/a :: S'encarrega del monitoratge del text, les seves versions, correccions, estructuració, etcètera. Pot coincidir o no amb algun dels autors. Es tracta, en definitiva, d'un coordinador de la col·laboració del text. És funció de l'editor sol·licitar les revisions i llegir-les.

Autor/a :: Són autors els qui pròpiament han redactat el text. L'ordre dels autors en reflecteix la contribució; el primer nom és el de qui més ha escrit. L’autor haurà llegit i revisat el text en la seva versió final o en versions anteriors, però no cal que estigui d'acord amb la configuració final del text. Aquesta tasca queda en mans de l'editor.

Contribuïdor/a :: Aquí poden considerar-se dos grups de contribuïdors. D'una banda, les persones encarregades de la revisió acadèmica del document (en cas que la seva contribució sigui considerable) i, de l’altra, col·laboradors externs la contribució dels quals hagi estat valuosa i s'hagi consolidat en parts de text incloses al document. La diferència entre contribuïdor i autor queda en mans de l'editor o de la resta d'autors però, en tot cas, la contribució ha de ser inferior a la de la resta d'autors. Com a regla general, si un autor ha escrit menys del 10% del text s'hauria de considerar contribuïdor. Al seu torn, ser contribuïdor requereix almenys haver escrit dos o tres paràgrafs.

Participant :: Es tracta d'una persona que, sense haver contribuït amb una part de text específica al document, ha fet contribucions de valor, com ara comentaris pertinents, o ha proporcionat criteris, referències o elements de discussió valuosos.

Revisor/a :: Aquesta tasca inclou una lectura minuciosa de tot el text, la correcció d'errors i la proposta de millores. En general, és una feina per encàrrec (sol·licitada a una persona que es considera competent en la matèria), encara que és possible que algú contribueixi fent una revisió sense sol·licitud expressa. En tal cas, la profunditat i qualitat d'aquesta es poden valorar per considerar aquesta persona revisora.footnote:[Aquesta divisió i especificació de nivells d'autoria s'ha copiat directament dels criteris establerts en el projecte http://floksociety.org/[FLOK Society - Buen conocer] (veure http://book.floksociety.org/ec/[el llibre del mateix títol, Barandiaran et al. 2015], pàgines 38-39).]
// end::contributing[]
